# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('EndPoint', models.CharField(max_length=256)),
                ('RegionName', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='RunningCloudTable',
            fields=[
                ('CloudName', models.CharField(max_length=256)),
                ('CloudId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('CloudType', models.CharField(max_length=64)),
                ('CloudCat', models.CharField(max_length=64)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'RunningCloudTable',
            },
        ),
        migrations.CreateModel(
            name='SecurityGroup',
            fields=[
                ('GroupId', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('GroupName', models.CharField(blank=True, max_length=256)),
                ('Description', models.TextField(blank=True)),
                ('OwnerId', models.CharField(blank=True, max_length=256)),
                ('ingress', models.TextField(blank=True)),
                ('egress', models.TextField(blank=True)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
                ('CloudId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cloud_plugin.RunningCloudTable')),
            ],
            options={
                'db_table': 'securityGroup',
            },
        ),
        migrations.CreateModel(
            name='SmIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Component', models.CharField(max_length=256)),
                ('Resource', models.CharField(max_length=256)),
                ('Name', models.CharField(max_length=256)),
                ('Region', models.CharField(max_length=256)),
                ('Action', models.CharField(max_length=256)),
                ('Issue', models.TextField(blank=True)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'issues',
            },
        ),
        migrations.CreateModel(
            name='Vpc',
            fields=[
                ('VpcId', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('apiDump', models.CharField(max_length=256)),
                ('IsDefault', models.BooleanField(default=True)),
                ('State', models.CharField(max_length=256)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
                ('CloudId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cloud_plugin.RunningCloudTable')),
                ('RegionName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_plugin.Region')),
            ],
            options={
                'db_table': 'vpc',
            },
        ),
        migrations.AddField(
            model_name='securitygroup',
            name='VpcId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cloud_plugin.Vpc'),
        ),
        migrations.AddField(
            model_name='region',
            name='CloudId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cloud_plugin.RunningCloudTable'),
        ),
    ]
